services:
  - type: web
    name: safestride-frontend
    env: static
    buildCommand: ""
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
